### ISSUE TITLE
mixed-citation support

### ISSUE THREAD

**Issue by lpanebr** [PeerJ/jats-conversion#101]
I am just starting to test this and noticed it does not support `mixed-citation`.

Any plans to support it and/or ideas as how should I go about doing it?

**Comment by hubgit** [comment]
There are no immediate plans to support `mixed-citation` (we're adding elements only as we use them, and we're only using `element-citation` for references), but if you wanted to add support you'd need to make an XSL template equivalent to [the existing one for element-citation](https://github.com/PeerJ/jats-conversion/blob/master/src/data/xsl/jats-to-html/citation.xsl) and match `mixed-citation` in [jats-to-html.xsl](https://github.com/PeerJ/jats-conversion/blob/master/src/data/xsl/jats-to-html.xsl#L706)

**Comment by lpanebr** [comment]
Thank you.
