### ISSUE TITLE
FIXED ERROR mktemp: too few X's in template 'validate'

### ISSUE THREAD

**Issue by lpanebr** [PeerJ/jats-conversion#126]
I was getting `mktemp: too few X's in template 'validate'` error and `I/O error : Permission denied` errors.

I fixed it by adding the `-XXX` on the command in [line 19](https://github.com/PeerJ/jats-conversion/blob/master/tests/validate.sh#L19) if `tests/validate.sh`

``` bash
OUTPUT_DIR=$(mktemp -d -t validate-XXX)
```

**Comment by hubgit** [comment]
Thanks @lpanebr! As the OS X version of `mktemp` wasn't complaining, which system was it failing on without the template X's?

**Comment by lpanebr** [comment]
You're welcome!

It was failing in Ubuntu.

**Comment by hubgit** [comment]
Fixed in https://github.com/PeerJ/jats-conversion/commit/2ef1a343a73839ade52e61481c940e56bd42be5b
