### ISSUE TITLE
can I use your code?

### ISSUE THREAD

**Issue by lpanebr** [PeerJ/jats-conversion#128]
What license is this repo code under?

I would like to use it to generate article fulltext html from JATS XML.

**Comment by lpanebr** [comment]
@hubgit is this code distributed under some CC license??

**Comment by hubgit** [comment]
The XSL and PHP files in /src are MIT-licensed:
https://github.com/PeerJ/jats-conversion/blob/master/src/LICENSE

The files in /schema are collected from various sources, so not covered by that license.

**Comment by GrazingScientist** [comment]
You suggest putting the LICENSE file into the root folder. Then GitHub shows very prominently the license label. Otherwise people may leave your project, because they think it does not have a license (and hence is not officially open source).
