### ISSUE TITLE
generateRDF use RIS stylesheet

### ISSUE THREAD

**Issue by keisetsu** [PeerJ/jats-conversion#129]
This may be by design, but in line 135 of `JATS.php`, 'jats-to-ris' is used for `generateRDF`. A `jats-to-rdf.xls` does exist alongside `jats-to-ris.xls`, so perhaps that should be used?

**Comment by hubgit** [comment]
That is indeed a bug - thanks for pointing it out.

Fixed in https://github.com/PeerJ/jats-conversion/commit/ce274175b6a8ce905e19926f161ff5cc1b1e3611
